### ISSUE TITLE
Get Different Error for GEMM testing

### ISSUE THREAD

**Issue by PatricZhao** [brodieG/treeprof#4]
I found your package from stackoverflow and I think it will be very useful for me.

Testing on Windows w/  R 3.3.0 (64bits) with Rstudio

However, several errors as below:
1. Can't pass self testing
> library("treeprof")
> treeprof(bench_mark_me())
Profiling
Timing stopped at: 0 0 0 
Error in eval(expr, envir, enclos) : 
  could not find function "bench_mark_me"
Error in run_rprof(expr.quoted = expr.capt, interval = interval, target.time = target.time,  : 
  Failed attempting to evaluate argument `expr.quoted`; see previous error.

2. Can't work for GEMM
```
> A <- matrix(runif(10000), nrow=100)
> B <- matrix(runif(10000), nrow=100)
> treeprof(C <- A %*% B)
Profiling
Estimate evaluation time
Fast Loop, still estimating
[1] 0.00 0.03
Looping to 5 seconds
[1] 0.00 0.03 5.66
Parsing Rprof
Error in parse_lines(lines$file) : 
  Log file in unexpected format; make sure you are not using function  names that contain double-quote characters.
```
```
> treeprof(C <- A %*% B)
Profiling
Estimate evaluation time
Fast Loop, still estimating
[1] 0.00 0.04
Looping to 5 seconds
[1] 0.00 0.04 4.32
Parsing Rprof
Done
Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  invalid 'nsmall' argument
In addition: Warning messages:
1: In max(n) : no non-missing arguments to max; returning -Inf
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
5: In min(x) : no non-missing arguments to min; returning Inf
6: In max(x) : no non-missing arguments to max; returning -Inf
7: In max(x) : no non-missing arguments to max; returning -Inf
8: In time_format(time_scale(c(x.cp$n, x.cp$n.self)/ticks.total * time.per,  :
  NaNs produced
> C <- A %*% B
> str(C)
 num [1:100, 1:100] 22.2 24.1 25.3 21.6 21.9 ...
```

**Comment by brodieG** [comment]
Thanks for reporting the issue.  Can you try running:
```
treeprof(C <- matrix(replicate(100, 1:100) %*% matrix(replicate(100, 1:100), 100)))
```
This is equivalent to your test example, but involves non primitive functions which can't really be profiled as they don't produce stack traces.  The package should handle those more gracefully, but that is just a matter of providing a more useful error message.

Re: your first error, sorry that I need to ask, but are you sure that `benchmark_me()` is available from the global environment?  Where is that function defined?  Is it exported?  This seems to be a different issue than the one you run into with the matrix multiply.

**Comment by brodieG** [comment]
Ah, I see where you got `bench_mark_me`.  That's just a dummy function for documentation purposes, you need to actually provide your own function or define `bench_mark_me`.

**Comment by PatricZhao** [comment]
Hi brodieG,

Thanks for the quickly response! 

Yes, the method you provide can work. But in real cases, I can't create matrices and do GEMM together since the data is already in there or from other functions. I suggest improving the functionality. Actually, the output from `treeprof` is very user-friendly and I like it!

The `bench_mark_me` from my original understanding should be a self-contained function to test if the package installed correctly. Obviously, my understanding is incorrect :(

I will try to use this package for other tests  tomorrow :)

Thanks again.

--Peng

**Comment by PatricZhao** [comment]
BTW, more testing on GEMM, so I think `treeprof` cam align with `Rprof` with more friendly output and that why we need it.

```
> B <- matrix(runif(1000000), nrow=1000)
> A <- matrix(runif(1000000), nrow=1000)
> Rprof()
> C <- A %*% B
> Rprof(NULL)
> summaryRprof()
$by.self
      self.time self.pct total.time total.pct
"%*%"      0.86      100       0.86       100

$by.total
      total.time total.pct self.time self.pct
"%*%"       0.86       100      0.86      100

$sample.interval
[1] 0.02

$sampling.time
[1] 0.86
```

**Comment by brodieG** [comment]
I guess all I'm saying is that I can reproduce your failure with the very simple top level primitive call.  You are right that it should probably work, but that is a trivial case that doesn't really benefit from `treeprof` since it is a single function call.  If all you're doing is a matrix multiply then I recommend you use `microbenchmark`.

Re: `bench_mark_me()`, you can replace it with any expression.  For example:
```
treeprof({
  A <- matrix(runif(1e4), 100)
  B <- matrix(runif(1e4), 100)
  C <- A %*% B
})
```
will work.  `bench_mark_me()` doesn't actually exist.  I was just trying to be cute in the documentation by providing a sample expression with a descriptive name.

Also *please re-install the package* as I just pushed an update to the master branch.

**Comment by PatricZhao** [comment]
@brodieG Thanks a lot! I understand your points about primitive call.

**Comment by PatricZhao** [comment]
FYI, this is one of our benchmarks that why we really care about GEMM even it's primitive call in R.

[R HPAC Benchmark](http://www.parallelr.com/r-hpac-benchmark-analysis/)

**Comment by brodieG** [comment]
Got it, though again, keep in mind that `treeprof` and all other `Rprof` based tools are only really useful for profiling R call stacks.  If all you want is the timing of a single primitive call you are much better of using `microbenchmark` or even just `system.time`.  It looks like the stuff you are doing is mostly timing calls and varying the underlying execution infrastructure.  `treeprof` is designed to find the chokepoints in the R call stack.

**Comment by PatricZhao** [comment]
Re-install and see you update on the error message, thanks.

```
> library(devtools)
> install_github("brodieG/treeprof")
Downloading GitHub repo brodieG/treeprof@master
from URL https://api.github.com/repos/brodieG/treeprof/zipball/master
Installing treeprof
"E:/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/patricz/AppData/Local/Temp/RtmpyOcvgg/devtools18481e221b5/brodieG-treeprof-3f4e2ae"  \
  --library="E:/R-3.3.0/library" --install-tests 

* installing *source* package 'treeprof' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (treeprof)
> library(treeprof)
> A <- matrix(runif(10000), nrow=100)
> B <- matrix(runif(10000), nrow=100)
> treeprof(C <- A %*% B)
Profiling
auto gc: running without gc() first
First run in 0 seconds
Fast Loop, still estimating required repetitions
Fast Loop, still estimating required repetitions
Looping to 5 seconds
Parsing Rprof
Error in parse_lines(lines, collapse.recursion) : 
  Internally inconsistent profile log file; first mismatch at:

"Rprof" 
```

**Comment by brodieG** [comment]
Can you try:
```
treeprof({A <- matrix(runif(10000), nrow=100); B <- matrix(runif(10000), nrow=100); C <- A %*% B})
```
The single primitive call definitely doesn't work, though I get a different error than yours.  The above works for me.  I'm also running this on a mac and I haven't tested treeprof on windows machines, and there are definitely some formatting differences in the profile files that could cause problems.

**Comment by PatricZhao** [comment]
I understand the issue and just let you know the latest output from my system :)

Thanks, I think we can close the bug.

**Comment by brodieG** [comment]
Thanks for reporting.
